name: Cron Example

on:
  # schedule:
  #   - cron: "* * * * *"
  workflow_dispatch:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    # set the jobs working folder to the cron-example subfolder within the main repo
    defaults:
      run:
        working-directory: cron-example

    steps:
      - uses: actions/checkout@v4

      # Setup Nodejs
      - name: Setup Node.js 12
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "12.x"

      # Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Install libraries
      # lockfile installs only the exact version of the dependencies files e.g. exact version hash not just the latest
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run tests
      - name: Run tests
        run: yarn test
