name: Pull Request Example

# restrict the pull request trigger to a specific folder in the repo
# If paths: is NOT set then ANY pull request againsta main will trigger this workflow even if the PR is against
# a differnt folder in the repo

on:
  pull_request:
    branches:
      - main
    paths:
      - typescript-project/** # pull request locked down to this folder only
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: typescript-project

    # download my repo into the runner vm
    steps:
      - uses: actions/checkout@v4

      # Setup Nodejs
      - name: Setup Node.js 16
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: typescript-project/yarn.lock

      # Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Install libraries
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run linting
      - name: Run linting
        run: yarn lint

      # Compile the code
      - name: Build project
        run: yarn build

      # Run tests
      - name: Run tests
        run: yarn test
